### ISSUE TITLE
SC marketplace contract set approval for transfer

### ISSUE THREAD

**Issue by richardkingxyz** [Hotpot-protocol1/marketplace-contracts#1]
Current:
The current openzeppling marketplace contract 'transfer's the NFT into the contract instead of setting approval for transfer which is incorrect.

When a user lists an NFT on opensea, it doesn't mean they lose custody of the NFT, they can also list the same NFT on looksrare or Blur.

So the current marketplace contract is wrong and must be upgraded and deployed on goerli

User Story:

This is her first time listing this collection so she pays for a one-time collection approval (The 2nd time she lists any coolcat from the same collection, this process does ot occur). After approval, she pay then a ETH Gas transaction for listing the NFT* 
Process on Blur:
Go to profile
Click list item and choose settings:
Duration
Price
Marketplaces you’d like to list on
Royalties
If it’s the first time you’re listing that collection with that wallet, you’ll HAVE to pay gas to approve Blur to have access to transfer your NFTs from that collection
NFTs do NOT leave your wallet
After you pay that gas, a signature approval will pop up, asking you to sign and confirm the listing (NO GAS FOR THIS)
If you list ANY nft from that collection again, you’ll be able to list without paying gas→ a signature approval will pop up to confirm that you’d like to list

[go to full user story](https://docs.google.com/document/d/1nmFIG0i5pSncZgH4lM7eIJA0FFCXDCBr9NZYlqCHWxY/edit#bookmark=id.ub5r0ko12xeo)

**Comment by statskiy-sovetnik** [comment]
This is already handled by frontend, no need to update smart contracts. Moving to "done"
